import { Subscription                                                      } from 'rxjs'                          ;
import { Component, ViewChild, OnInit, OnDestroy, EventEmitter, ElementRef } from '@angular/core'                 ;
import { NgZone, Renderer, AfterViewInit, ApplicationRef,                  } from '@angular/core'                 ;
import { ComponentFactoryResolver, ViewContainerRef, ApplicationInitStatus } from '@angular/core'                 ;
import { trigger, transition, animate, style, query, animateChild, state,  } from '@angular/animations'           ;
import { group, useAnimation, stagger,                                     } from '@angular/animations'           ;
import { Nav, Platform, MenuController, ModalController,                   } from 'ionic-angular'                 ;
import { NavOptions,                                                       } from 'ionic-angular'                 ;
import { ModalOptions,                                                     } from 'ionic-angular'                 ;
import { Log, CONSOLE, moment, Moment, oo, JSON5, blobUtil, Duration,      } from 'domain/onsitexdomain'          ;
import { ooPatch, ooPointer, sizeOf, round, roundMaxDecimals,              } from 'domain/onsitexdomain'          ;
import { Employee, Shift, Report, ReportOther, Invoice, DPS, PreAuth,      } from 'domain/onsitexdomain'          ;
import { Jobsite, Address, Street, OnSiteGeolocation, Schedule, Schedules, } from 'domain/onsitexdomain'          ;
import { Timesheet,                                                        } from 'domain/onsitexdomain'          ;
import { PayrollPeriod                                                     } from 'domain/onsitexdomain'          ;
import { PayrollPeriods                                                    } from 'domain/onsitexdomain'          ;
import { Message                                                           } from 'domain/onsitexdomain'          ;
import { Jobsites,                                                         } from 'domain/onsitexdomain'          ;
import { ReportLogistics,                                                  } from 'domain/onsitexdomain'          ;
import { ScheduleBeta,                                                     } from 'domain/onsitexdomain'          ;
import { OnSiteCoordinates, OnSiteGeoposition,                             } from 'domain/onsitexdomain'          ;
import { LatLng, LatLonLiteral,                                            } from 'domain/onsitexdomain'          ;
import { DatabaseProgress,                                                 } from 'domain/onsitexdomain'          ;
import { Employee as NewEmployee,                                          } from 'domain/newdomain'              ;
import { Jobsite as NewJobsite,                                            } from 'domain/newdomain'              ;
